### PR TITLE
Chaning back userAction from flat object to key-value object

### LINKED ISSUE #351: Purchased land Etherscan link using string “actionId” rather than the actionId

### PR DESCRIPTION
**Pull request by marcelomorgado**
### Issue link

#351 

### Auto-close the issue?

Closes #351 

### Types of changes

Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

**Comment by pcowgill** [comment]
Thanks for the quick fix!

**Comment by pcowgill** [comment]
@marcelomorgado I was going to merge this but CI is failing

**Comment by pcowgill** [comment]
> @marcelomorgado I was going to merge this but CI is failing

I see you just fixed this!

**Comment by marcelomorgado** [comment]
> @marcelomorgado Think users who have already run the last version of develop will have a smooth upgrade path?

Yes

**Comment by pcowgill** [comment]
> Yes

On the data storage side, will there be anything like an extra key / value for the actions where the key is the string “actionId”? I haven’t through that carefully, but if that were the case, even if the user won’t see that, wondering if we want to clean that up to prevent uncaught exceptions later.

**Comment by marcelomorgado** [comment]
This bug (accountId prop instead of '0x123' prop) was occured on the process that get data (`fromKey->toFlat->find`) from storage and parse it to the component.
The fix was to add an `->toKey` after the find.
So, no storage data was changed with this wrongly prop.

**Comment by pcowgill** [comment]
> This bug (accountId prop instead of '0x123' prop) was occured on the process that get data (`fromKey->toFlat->find`) from storage and parse it to the component.
> The fix was to add an `->toKey` after the find.
> So, no storage data was changed with this wrongly prop.

Oh okay, that's great! Thanks for that explanation. Makes sense.

**Pull request merged**
