### PR TITLE
Changing config to point to localhost node

### LINKED ISSUE #110: Change demo app config to point to localhost so it works on any local machine

### PR DESCRIPTION
**Pull request by marcelomorgado**
### Issue link

#110 

### Auto-close the issue?

Closes #110 

### Types of changes

Technical debt (a code change that doesn't fix a bug or add a feature but makes something clearer for devs)

### CODE REVIEW

**Comment by pcowgill** [comment]
@marcelomorgado This is working for you locally, right?

**Comment by marcelomorgado** [comment]
> @marcelomorgado This is working for you locally, right?

I'm testing the app from my mobile device, because of that I'm using external IP from my computer. I think that localhost is for developers that are using a simulator to test the app.

**Comment by pcowgill** [comment]
@marcelomorgado Ah ok - I'll confirm that it's working on my machine using the simulator before merging, then.

**Comment by pcowgill** [comment]
@marcelomorgado This is working for me on the iOS simulator with localhost, so we can merge it

**Comment by pcowgill** [comment]
Oh FYI, the localhost change isn't part of this diff anymore because that made it through in another PR already

**Pull request merged**
