### PR TITLE
Implement Storybook

### PR DESCRIPTION
**Pull request by mseijas**
### Auto-close the issue?

Closes https://github.com/tasitlabs/tasit/issues/32
Closes https://github.com/tasitlabs/tasit/issues/98

### Types of changes

Technical debt (a code change that doesn't fix a bug or add a feature but makes something clearer for devs)

### Notes

Note that the entry point of the app has been changed from `App.js` to `index.js`

`index.js` determines if the app should be loaded normally, or if storybook should be loaded instead. This is defined by the value passed to the `SHOW_STORYBOOK` boolean.

Additionally, there's a prestorybook hook that will run before the storybook server is executed, and that automatically generates `/storybook/storyLoader.js` and includes all the files inside `/components/` that match `**/*.story.js`

### CODE REVIEW

**Comment by marcelomorgado** [comment]
Thanks @mseijas!

We've refactored some components recently:

SellOrder was renamed to LandForSale
SellOrderClaim was renamed to BuyLand
SellOrderList was renamed to LandForSaleList
SellOrderListItem was renamed to LandForSaleListItem

Please, tell me if you need some help on conflicts because the code was changed/renamed too.

A question: Is possible to use storyboard from web to see the components instead of mobile?

**Comment by mseijas** [comment]
@marcelomorgado Hey so I tried rebasing with the new changes and it's been kind of a mess - there are so many changes to apply that I'm not confident that things are looking right after rebasing. I'm thinking it may be simpler to just start again on top of the newly merged changes to reduce the risk of overwriting or breaking anything. 

I'm thinking of maybe splitting it into different PRs to keep track of the changes more easily. Maybe one with folder reorganization and another one with storybook implementation. What are your thoughts on this?

**Comment by marcelomorgado** [comment]
> @marcelomorgado Hey so I tried rebasing with the new changes and it's been kind of a mess - there are so many changes to apply that I'm not confident that things are looking right after rebasing. I'm thinking it may be simpler to just start again on top of the newly merged changes to reduce the risk of overwriting or breaking anything.
> 
> I'm thinking of maybe splitting it into different PRs to keep track of the changes more easily. Maybe one with folder reorganization and another one with storybook implementation. What are your thoughts on this?

Hi,
Yeah, work from the updated `develop` seems a good idea and split PRs too.
Thanks!

**Comment by pcowgill** [comment]
@mseijas Yep, that sounds good. Sorry the timing for this PR ended up making it so complicated! I’ll close this one then.

**Comment by pcowgill** [comment]
@mseijas Feel free to message me on Twitter if you're about to work on this again, because I'll want to make sure there aren't any PRs in progress that would make it complicated for you a second time. Thanks!

**Comment by mseijas** [comment]
@pcowgill will do! this week is a bit crazy for me, so I’ll probably circle back to this early next week

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pcowgill** [comment]
@mseijas Sounds good. Thanks!!

**Pull request closed without merging**
